apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  labels:
    app: backend
type: Opaque
stringData:
  DATABASE_URL: postgresql+asyncpg://game_of_life:game_of_life@postgres:5432/game_of_life
