apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    app: postgres
type: Opaque
stringData:
  POSTGRES_DB: game_of_life
  POSTGRES_USER: game_of_life
  POSTGRES_PASSWORD: game_of_life
